config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'sessions' }

  scope '/api/v1' do
    resources :products, :product_variants, :stores
    get :csrf, to: 'csrf#index'
  end

  root 'index#index'

  get '*path', to: 'index#index'

end

app/models/product_variant.rb
class ProductVariant < ActiveRecord::Base
  # store_accessor :options, :Color

  belongs_to :product
end

app/controllers/product_variants_controller.rb
class ProductVariantsController < ApplicationController
  before_filter :authenticate_user_from_token!, except: [:index, :show]
  before_action :set_product_variant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /product_variants
  # GET /product_variants.json
  def index
    @product_variants = ProductVariant.all
    render :json => @product_variants
  end

  # GET /product_variants/1
  # GET /product_variants/1.json
  def show
    @product_variants = ProductVariant.find(params[:id])
    render :json => @product_variants
  end

  # GET /product_variants/new
  def new
    @product_variant = ProductVariant.new
  end

  # GET /product_variants/1/edit
  def edit
  end

  # POST /product_variants
  # POST /product_variants.json
  def create
    @product = Product.find(params[:product_id])
    @product_variant = @product.product_variants.new(product_variant_params)

    respond_to do |format|
      if @product_variant.save
        format.html { redirect_to product_path(@product), notice: 'Product variant was successfully created.' }
        format.json { render :show, status: :created, location: @product_variant }
      else
        format.html { render :new }
        format.json { render json: @product_variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_variants/1
  # PATCH/PUT /product_variants/1.json
  def update
    respond_to do |format|
      if @product_variant.update(product_variant_params)
        format.html { redirect_to @product_variant, notice: 'Product variant was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_variant }
      else
        format.html { render :edit }
        format.json { render json: @product_variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_variants/1
  # DELETE /product_variants/1.json
  def destroy
    @product_variant.destroy
    respond_to do |format|
      format.html { redirect_to product_variants_url, notice: 'Product variant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_variant
      @product_variant = ProductVariant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_variant_params
      params.require(:product_variant).permit(:options, :product_variant_number, :primary_photo_id, :product_id)
    end
end

app/helpers/product_variants_helper.rb
module ProductVariantsHelper
end

app/views/product_variants/_form.html.erb
<%= form_for(@product_variant) do |f| %>
  <% if @product_variant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_variant.errors.count, "error") %> prohibited this product_variant from being saved:</h2>

      <ul>
      <% @product_variant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :options %><br>
    <%= f.text_field :options %>
  </div>
  <div class="field">
    <%= f.label :product_variant_number %><br>
    <%= f.text_field :product_variant_number %>
  </div>
  <div class="field">
    <%= f.label :primary_photo_id %><br>
    <%= f.number_field :primary_photo_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_variants/edit.html.erb
<h1>Editing Product Variant</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_variant %> |
<%= link_to 'Back', product_variants_path %>

app/views/product_variants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Product Variants</h1>

<table>
  <thead>
    <tr>
      <th>Options</th>
      <th>Product variant number</th>
      <th>Primary photo</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_variants.each do |product_variant| %>
      <tr>
        <td><%= product_variant.options %></td>
        <td><%= product_variant.product_variant_number %></td>
        <td><%= product_variant.primary_photo_id %></td>
        <td><%= product_variant.product_id %></td>
        <td><%= link_to 'Show', product_variant %></td>
        <td><%= link_to 'Edit', edit_product_variant_path(product_variant) %></td>
        <td><%= link_to 'Destroy', product_variant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product variant', new_product_variant_path %>

app/views/product_variants/new.html.erb
<h1>New Product Variant</h1>

<%= render 'form' %>

<%= link_to 'Back', product_variants_path %>

app/views/product_variants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Options:</strong>
  <%= @product_variant.options %>
</p>

<p>
  <strong>Product variant number:</strong>
  <%= @product_variant.product_variant_number %>
</p>

<p>
  <strong>Primary photo:</strong>
  <%= @product_variant.primary_photo_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @product_variant.product_id %>
</p>

<%= link_to 'Edit', edit_product_variant_path(@product_variant) %> |
<%= link_to 'Back', product_variants_path %>